INSERT INTO TB_USERS (NAME, EMAIL, PASSWORD) VALUES ('Bob', 'bob@gmail.com', '$2a$10$VJQfRjbkwfQBPjpNcVBiludN7SFHpiit7FxdDOdoBV89ingheris.');
INSERT INTO TB_USERS (NAME, EMAIL, PASSWORD) VALUES ('Alex', 'alex@gmail.com', '$2a$10$5GIS5mkD6fNrcU.JSANVgOpwvO2u/n9rWKg2xDSpwiZSAvQVrm5Ca');
INSERT INTO TB_USERS (NAME, EMAIL, PASSWORD) VALUES ('Chris', 'chris@gmail.com', '$2a$10$kBb9be9Sn3bNrI9V8Cksiu75JpvBRnHXYgTkVTtZCxy.CUuN0fr0u');

INSERT INTO TB_ROLES (ROLE_NAME) VALUES ('ROLE_OPERATOR');
INSERT INTO TB_ROLES (ROLE_NAME) VALUES ('ROLE_ADM');

INSERT INTO TB_USERS_ROLES (USER_ID, ROLE_ID) VALUES (1, 1);
INSERT INTO TB_USERS_ROLES (USER_ID, ROLE_ID) VALUES (2, 1);
INSERT INTO TB_USERS_ROLES (USER_ID, ROLE_ID) VALUES (2, 2);


